#ifndef EEPROM_PARAMS_H
#define EEPROM_PARAMS_H

enum basic_eeprom_offset {
    EEPROM_BOOT_BYTE = 0,
    EEPROM_LAYOUT_REVISION = 1,
    EEPROM_BOOT_LOADER_REVISION = 2,
    EEPROM_MAIN_REVISION = 3,
    EEPROM_SUB_REVISION = 4,
    EEPROM_NAME = 5,
    EEPROM_MOTOR_DIRECTION = 17,
    EEPROM_BIDIRECTIONAL_MODE = 18,
    EEPROM_SINUSOIDAL_STARTUP = 19,
    EEPROM_COMPLEMENTARY_PWM = 20,
    EEPROM_VARIABLE_PWM_FREQUENCY = 21,
    EEPROM_STUCK_ROTOR_PROTECTION = 22,
    EEPROM_TIMING_ADVANCE = 23,
    EEPROM_PWM_FREQUENCY = 24,
    EEPROM_STARTUP_POWER = 25,
    EEPROM_MOTOR_KV = 26,
    EEPROM_MOTOR_POLES = 27,
    EEPROM_BRAKE_ON_STOP = 28,
    EEPROM_STALL_PROTECTION = 29,
    EEPROM_BEEP_VOLUME = 30,
    EEPROM_INTERVAL_TELEMETRY = 31,
    EEPROM_SERVO_LOW_THRESHOLD = 32,
    EEPROM_SERVO_HIGH_THRESHOLD = 33,
    EEPROM_SERVO_NEUTRAL = 34,
    EEPROM_SERVO_DEAD_BAND = 35,
    EEPROM_LOW_VOLTAGE_CUTOFF = 36,
    EEPROM_LOW_VOLTAGE_THRESHOLD = 37,
    EEPROM_RC_CAR_REVERSING = 38,
    EEPROM_USE_HALL_SENSORS = 39,
    EEPROM_SINE_MODE_RANGE = 40,
    EEPROM_BRAKE_STRENGTH = 41,
    EEPROM_RUNNING_BRAKE_LEVEL = 42,
    EEPROM_TEMPERATURE_LIMIT = 43,
    EEPROM_CURRENT_LIMIT = 44,
    EEPROM_SINE_MODE_POWER = 45,
    EEPROM_ESC_PROTOCOL = 46,
    EEPROM_AUTO_ADVANCE = 47,
    EEPROM_STARTUP_MELODY = 48,
};

#define EEPROM_TUNE_MAX_LEN 128

#endif // EEPROM_PARAMS_H